services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    network_mode: host
    command: start-dev
  client:
    build: .
    container_name: oidc_client
    ports:
      - "8000:8000"
    network_mode: host
    command: ./start_client.sh
